In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
## Define the vocabulary size
voc_size=10000

In [6]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [7]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[3831, 175, 4015, 3651],
 [3831, 175, 4015, 786],
 [3831, 9078, 4015, 4123],
 [6628, 4850, 516, 8199, 9587],
 [6628, 4850, 516, 8199, 2820],
 [4082, 3831, 5098, 4015, 4415],
 [3522, 2507, 4802, 8199]]

In [ ]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding

from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

In [10]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 3831  175 4015 3651]
 [   0    0    0    0 3831  175 4015  786]
 [   0    0    0    0 3831 9078 4015 4123]
 [   0    0    0 6628 4850  516 8199 9587]
 [   0    0    0 6628 4850  516 8199 2820]
 [   0    0    0 4082 3831 5098 4015 4415]
 [   0    0    0    0 3522 2507 4802 8199]]


In [11]:
## feature representation
dim=10

In [12]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [13]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [14]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 169ms/step


array([[[-0.0206808 ,  0.01192906,  0.0221874 ,  0.02117142,
         -0.03357047, -0.04667462,  0.03792158, -0.03202099,
          0.03079608, -0.04832708],
        [-0.0206808 ,  0.01192906,  0.0221874 ,  0.02117142,
         -0.03357047, -0.04667462,  0.03792158, -0.03202099,
          0.03079608, -0.04832708],
        [-0.0206808 ,  0.01192906,  0.0221874 ,  0.02117142,
         -0.03357047, -0.04667462,  0.03792158, -0.03202099,
          0.03079608, -0.04832708],
        [-0.0206808 ,  0.01192906,  0.0221874 ,  0.02117142,
         -0.03357047, -0.04667462,  0.03792158, -0.03202099,
          0.03079608, -0.04832708],
        [ 0.03863338, -0.03875123, -0.00486124,  0.00768756,
         -0.01195798,  0.04768682,  0.03676615, -0.00771027,
          0.01275674,  0.0070891 ],
        [ 0.02204132, -0.01274798,  0.04968674,  0.02623894,
          0.04385263, -0.04041319,  0.0145291 ,  0.03917331,
          0.01651926,  0.04986319],
        [-0.03217687, -0.04023845, -0.00771232,  0.0

In [15]:
embedded_docs[0]

array([   0,    0,    0,    0, 3831,  175, 4015, 3651])

In [16]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 44ms/step


array([[-0.0206808 ,  0.01192906,  0.0221874 ,  0.02117142, -0.03357047,
        -0.04667462,  0.03792158, -0.03202099,  0.03079608, -0.04832708],
       [-0.0206808 ,  0.01192906,  0.0221874 ,  0.02117142, -0.03357047,
        -0.04667462,  0.03792158, -0.03202099,  0.03079608, -0.04832708],
       [-0.0206808 ,  0.01192906,  0.0221874 ,  0.02117142, -0.03357047,
        -0.04667462,  0.03792158, -0.03202099,  0.03079608, -0.04832708],
       [-0.0206808 ,  0.01192906,  0.0221874 ,  0.02117142, -0.03357047,
        -0.04667462,  0.03792158, -0.03202099,  0.03079608, -0.04832708],
       [ 0.03863338, -0.03875123, -0.00486124,  0.00768756, -0.01195798,
         0.04768682,  0.03676615, -0.00771027,  0.01275674,  0.0070891 ],
       [ 0.02204132, -0.01274798,  0.04968674,  0.02623894,  0.04385263,
        -0.04041319,  0.0145291 ,  0.03917331,  0.01651926,  0.04986319],
       [-0.03217687, -0.04023845, -0.00771232,  0.01110492,  0.02065829,
         0.0339894 , -0.00501517,  0.02231355